version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - sleep 5
      - echo test > artifact
      - echo Build finished on `date`

artifacts:
  files:
    - artifact
